site_name: Sistemas dinámicos 

theme:
  name: "material"

nav:
  - Introducción: index.md
  - Explicación: explanation.md
  - Tutorial: tutorials.md
  - Referencias: reference.md

plugins:
  - mkdocstrings:


markdown_extensions:
  - pymdownx.arithmatex:
     generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

